const express = require('express');
const cors = require('cors');
require('dotenv').config();
const { OpenRouter } = require('@openrouter/sdk');

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors({
    origin: process.env.FRONTEND_URL || 'http://localhost:3000',
    credentials: true
}));
app.use(express.json());

// Rate limiting middleware
const rateLimit = require('express-rate-limit');
const limiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 50, // limit each IP to 50 requests per windowMs
    message: 'Too many requests from this IP, please try again later.'
});
app.use('/api/generate-image', limiter);

// Request validation middleware
const validateRequest = (req, res, next) => {
    const { prompt } = req.body;
    
    if (!prompt || typeof prompt !== 'string') {
        return res.status(400).json({ 
            error: 'Valid prompt is required',
            code: 'INVALID_PROMPT'
        });
    }
    
    if (prompt.trim().length === 0) {
        return res.status(400).json({ 
            error: 'Prompt cannot be empty',
            code: 'EMPTY_PROMPT'
        });
    }
    
    if (prompt.length > 1000) {
        return res.status(400).json({ 
            error: 'Prompt too long (max 1000 characters)',
            code: 'PROMPT_TOO_LONG'
        });
    }
    
    // Basic profanity/content filter
    const blockedTerms = [
        'hate speech',
        'violence',
        // Add more terms as needed
    ];
    
    const lowerPrompt = prompt.toLowerCase();
    for (const term of blockedTerms) {
        if (lowerPrompt.includes(term)) {
            return res.status(400).json({ 
                error: 'Prompt contains restricted content',
                code: 'CONTENT_VIOLATION'
            });
        }
    }
    
    next();
};

// Initialize OpenRouter
let openrouter;
try {
    const apiKey = process.env.OPENROUTER_API_KEY;
    if (!apiKey) {
        throw new Error('OPENROUTER_API_KEY is not set in environment variables');
    }
    
    openrouter = new OpenRouter({
        apiKey: apiKey
    });
    
    console.log('✅ OpenRouter initialized successfully');
} catch (error) {
    console.error('❌ Failed to initialize OpenRouter:', error.message);
    process.exit(1);
}

// Security headers middleware
app.use((req, res, next) => {
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('X-Frame-Options', 'DENY');
    res.setHeader('X-XSS-Protection', '1; mode=block');
    next();
});

// Health check endpoint
app.get('/api/health', (req, res) => {
    res.json({ 
        status: 'ok',
        service: 'Cyber Image Generator API',
        version: '1.0.0',
        environment: process.env.NODE_ENV || 'development'
    });
});

// Generate image endpoint with validation
app.post('/api/generate-image', validateRequest, async (req, res) => {
    try {
        const { prompt, model } = req.body;
        
        // Log request (without exposing sensitive info)
        console.log(`📸 Image generation requested - Prompt length: ${prompt.length}, Model: ${model || 'default'}`);
        
        const result = await openrouter.chat.send({
            model: model || "black-forest-labs/flux.2-klein-4b",
            messages: [{
                role: "user",
                content: prompt
            }],
            modalities: ["image"],
            provider: {
                "sort": "throughput"
            }
        });
        
        const message = result.choices[0].message;
        
        if (message.images && message.images.length > 0) {
            res.json({
                success: true,
                images: message.images.map((img, index) => ({ 
                    url: img.image_url.url,
                    index: index + 1
                })),
                prompt: prompt,
                model: model || "black-forest-labs/flux.2-klein-4b",
                generatedAt: new Date().toISOString()
            });
            
            console.log(`✅ Image generated successfully`);
        } else {
            throw new Error('No images generated by AI');
        }
    } catch (error) {
        console.error('❌ Image generation error:', error.message);
        
        // User-friendly error messages
        let errorMessage = 'Failed to generate image';
        let statusCode = 500;
        
        if (error.message.includes('API key') || error.message.includes('authentication')) {
            errorMessage = 'Service authentication error';
            statusCode = 503;
        } else if (error.message.includes('rate limit') || error.message.includes('quota')) {
            errorMessage = 'Service temporarily unavailable. Please try again later.';
            statusCode = 429;
        } else if (error.message.includes('content policy')) {
            errorMessage = 'Prompt violates content policy';
            statusCode = 400;
        }
        
        res.status(statusCode).json({ 
            success: false,
            error: errorMessage,
            details: process.env.NODE_ENV === 'development' ? error.message : undefined
        });
    }
});

// Available models endpoint
app.get('/api/models', (req, res) => {
    res.json({
        success: true,
        models: [
            {
                id: "flux-pro",
                name: "Cyber Flux Pro",
                description: "High-quality image generation",
                maxPromptLength: 500
            },
            {
                id: "secure-vision",
                name: "Secure Vision",
                description: "Enhanced detail and clarity",
                maxPromptLength: 500
            },
            {
                id: "quantum-render",
                name: "Quantum Render",
                description: "Advanced rendering technology",
                maxPromptLength: 500
            }
        ]
    });
});

// Error handling middleware
app.use((err, req, res, next) => {
    console.error('🚨 Server error:', err.stack);
    res.status(500).json({
        success: false,
        error: 'Internal server error',
        code: 'INTERNAL_ERROR'
    });
});

// 404 handler
app.use('*', (req, res) => {
    res.status(404).json({
        success: false,
        error: 'Endpoint not found',
        code: 'NOT_FOUND'
    });
});

// Graceful shutdown
process.on('SIGTERM', () => {
    console.log('SIGTERM received. Shutting down gracefully...');
    server.close(() => {
        console.log('Server closed');
        process.exit(0);
    });
});

// Start server
const server = app.listen(PORT, () => {
    console.log(`
    🚀 Cyber Image Generator API
    ==============================
    ✅ Server running on port: ${PORT}
    ✅ Environment: ${process.env.NODE_ENV || 'development'}
    ✅ Health check: http://localhost:${PORT}/api/health
    ✅ Frontend URL: ${process.env.FRONTEND_URL || 'Not configured'}
    ==============================
    `);
});
