const express = require('express');
const cors = require('cors');
const axios = require('axios');
const path = require('path');
const fs = require('fs');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 10000;

// Enhanced CORS configuration
const corsOptions = {
    origin: function (origin, callback) {
        // Allow all in development
        if (!origin || process.env.NODE_ENV === 'development') {
            callback(null, true);
        } else {
            // Allow localhost and specific domains in production
            const allowedOrigins = [
                'http://localhost:10000',
                'http://localhost:3000',
                'http://127.0.0.1:10000',
                'http://127.0.0.1:3000',
                'https://image-ai-p2uj.onrender.com',
                'https://your-frontend-domain.com'
            ];
            
            if (allowedOrigins.includes(origin) || 
                origin.includes('localhost') || 
                origin.includes('127.0.0.1') ||
                origin.includes('render.com')) {
                callback(null, true);
            } else {
                console.log('Blocked by CORS:', origin);
                callback(new Error('Not allowed by CORS'));
            }
        }
    },
    credentials: true,
    methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE'],
    allowedHeaders: ['Content-Type', 'Authorization', 'Accept'],
    exposedHeaders: ['Content-Length', 'X-Request-Id'],
    maxAge: 86400 // 24 hours
};

// Apply CORS
app.use(cors(corsOptions));

// Handle preflight requests
app.options('*', cors(corsOptions));

// Middleware
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Get API key
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;

// Check if frontend folder exists
const frontendPath = path.join(__dirname, 'frontend');
const indexPath = path.join(frontendPath, 'index.html');

if (fs.existsSync(indexPath)) {
    // Serve from frontend folder
    app.use(express.static(frontendPath));
    console.log('✅ Serving from /frontend folder');
} else {
    // Serve from root (for Render deployment)
    app.use(express.static(__dirname));
    console.log('⚠️  Frontend folder not found, serving from root');
}

// Health check
app.get('/api/health', (req, res) => {
    res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
    res.json({ 
        status: 'ok',
        service: 'Cyber Image Generator',
        timestamp: new Date().toISOString(),
        cors: 'enabled',
        port: PORT,
        environment: process.env.NODE_ENV || 'development'
    });
});

// Detailed health check
app.get('/api/debug', (req, res) => {
    res.json({
        headers: req.headers,
        origin: req.headers.origin,
        host: req.headers.host,
        method: req.method,
        url: req.url,
        timestamp: new Date().toISOString(),
        corsEnabled: true
    });
});

// Generate image
app.post('/api/generate-image', async (req, res) => {
    try {
        // Set CORS headers
        res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
        res.header('Access-Control-Allow-Credentials', 'true');
        
        const { prompt, model } = req.body;
        
        if (!prompt) {
            return res.status(400).json({ 
                success: false,
                error: 'Prompt is required' 
            });
        }
        
        console.log('Generating image for:', prompt.substring(0, 100));
        console.log('Using model:', model || 'default');
        
        // Use the provided model or default
        const imageModel = model || "black-forest-labs/flux.2-klein-4b";
        
        const response = await axios.post('https://openrouter.ai/api/v1/chat/completions', {
            model: imageModel,
            messages: [{ role: "user", content: prompt }],
            modalities: ["image"]
        }, {
            headers: {
                'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
                'Content-Type': 'application/json',
                'HTTP-Referer': req.headers.origin || 'http://localhost:10000',
                'X-Title': 'Cyber Image Generator'
            },
            timeout: 30000 // 30 seconds timeout
        });
        
        const images = response.data.choices[0].message.images;
        
        if (!images || images.length === 0) {
            throw new Error('No image generated by AI');
        }
        
        res.json({
            success: true,
            images: images.map(img => ({ 
                url: img.image_url.url,
                size: img.image_url.size 
            })),
            prompt: prompt,
            model: imageModel,
            generatedAt: new Date().toISOString()
        });
        
    } catch (error) {
        console.error('❌ Error generating image:', error.message);
        console.error('Error details:', error.response?.data || error.stack);
        
        // Set CORS headers for error response too
        res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
        
        res.status(500).json({ 
            success: false,
            error: error.message || 'Failed to generate image',
            details: error.response?.data || null,
            timestamp: new Date().toISOString()
        });
    }
});

// Test endpoint
app.get('/api/test-cors', (req, res) => {
    res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
    res.json({
        message: 'CORS test successful!',
        origin: req.headers.origin,
        timestamp: new Date().toISOString(),
        cors: 'working'
    });
});

// Serve index.html for all routes
app.get('*', (req, res) => {
    // Set CORS headers for HTML responses too
    res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
    
    // Try frontend folder first, then root
    const possiblePaths = [
        path.join(__dirname, 'frontend', 'index.html'),
        path.join(__dirname, 'index.html'),
        path.join(__dirname, 'public', 'index.html')
    ];
    
    for (const filePath of possiblePaths) {
        if (fs.existsSync(filePath)) {
            return res.sendFile(filePath);
        }
    }
    
    // If no index.html found, send simple response
    res.send(`
        <!DOCTYPE html>
        <html>
        <head>
            <title>Cyber Image Generator</title>
            <style>
                body { 
                    font-family: Arial, sans-serif; 
                    text-align: center; 
                    padding: 50px; 
                    background: #0f172a;
                    color: #ffffff;
                }
                h1 { color: #3b82f6; }
                .container {
                    max-width: 600px;
                    margin: 0 auto;
                    padding: 30px;
                    background: #1e293b;
                    border-radius: 10px;
                    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                }
                .status {
                    color: #10b981;
                    font-weight: bold;
                }
                code {
                    background: #334155;
                    padding: 2px 6px;
                    border-radius: 4px;
                    font-family: monospace;
                }
                a {
                    color: #60a5fa;
                    text-decoration: none;
                }
                a:hover {
                    text-decoration: underline;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🚀 Cyber Image Generator API</h1>
                <p class="status">✅ Backend is running!</p>
                <p>Frontend files not found in expected locations.</p>
                
                <div style="text-align: left; margin: 30px 0; background: #0f172a; padding: 20px; border-radius: 8px;">
                    <h3>📡 API Endpoints:</h3>
                    <ul>
                        <li>Health Check: <a href="/api/health"><code>/api/health</code></a></li>
                        <li>Generate Image (POST): <code>/api/generate-image</code></li>
                        <li>CORS Test: <a href="/api/test-cors"><code>/api/test-cors</code></a></li>
                        <li>Debug Info: <a href="/api/debug"><code>/api/debug</code></a></li>
                    </ul>
                </div>
                
                <p>Upload your frontend files to:</p>
                <code>${__dirname}</code>
                
                <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #334155;">
                    <p>Made with ❤️ by Team Cybersecurity</p>
                </div>
            </div>
        </body>
        </html>
    `);
});

// Error handling middleware
app.use((err, req, res, next) => {
    console.error('Global error:', err);
    
    res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
    res.header('Access-Control-Allow-Credentials', 'true');
    
    res.status(err.status || 500).json({
        success: false,
        error: err.message || 'Internal Server Error',
        timestamp: new Date().toISOString()
    });
});

// Start server
const server = app.listen(PORT, () => {
    console.log(`
    🚀 Cyber Image Generator
    ========================
    Port: ${PORT}
    Mode: ${process.env.NODE_ENV || 'development'}
    URL: http://localhost:${PORT}
    CORS: ✅ Enabled
    ========================
    `);
    
    // Log available endpoints
    console.log('\n📡 Available Endpoints:');
    console.log('   • GET  /api/health     - Health check');
    console.log('   • GET  /api/debug      - Debug info');
    console.log('   • GET  /api/test-cors  - CORS test');
    console.log('   • POST /api/generate-image - Generate images');
    console.log('   • GET  /*              - Frontend\n');
});

// Handle graceful shutdown
process.on('SIGTERM', () => {
    console.log('SIGTERM received. Shutting down gracefully...');
    server.close(() => {
        console.log('Server closed.');
        process.exit(0);
    });
});

process.on('SIGINT', () => {
    console.log('SIGINT received. Shutting down gracefully...');
    server.close(() => {
        console.log('Server closed.');
        process.exit(0);
    });
});
